model "/home/juano/Desktop/02_20_VRP_2/sp1.mod";
model "/home/juano/Desktop/02_20_VRP_2/mp.mod";
data "/home/juano/Desktop/02_20_VRP_2/data0.dat";
data "/home/juano/Desktop/02_20_VRP_2/data1.dat";
data "/home/juano/Desktop/02_20_VRP_2/data2.dat";
data "/home/juano/Desktop/02_20_VRP_2/data3.dat";
param Out symbolic := "/home/juano/Desktop/02_20_VRP_2/_salida_5.txt";
option log_file "/home/juano/Desktop/02_20_VRP_2/_log_5.txt";
include "/home/juano/Desktop/02_20_VRP_2/prob.run";